package com.catani.zar;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * ZarDatosPersonales generated by hbm2java
 */
public class ZarDatosPersonales implements java.io.Serializable {

	private Integer id;
	private String foto;
	private String primerNombre;
	private String segundoNombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private boolean sexo;
	private String cedula;
	private String email;
	private Date fechaDeNacimiento;
	private String nacionalidad;
	private String direccionDomicilio;
	private Boolean discapacidad;
	private String telefonoFijo;
	private Boolean movilizacionPropia;
	private Boolean licencia;
	private Float salarioActual;
	private Float aspiracionSalarial;
	private int idEstadoCivil;
	private int idCiudadResidencia;
	private Integer idTipoDiscapacidad;
	private Integer idTipoLicencia;

	public ZarDatosPersonales() {
	}

	public ZarDatosPersonales(String primerNombre, String apellidoPaterno,
			boolean sexo, String cedula, String email, Date fechaDeNacimiento,
			String nacionalidad, int idEstadoCivil, int idCiudadResidencia) {
		this.primerNombre = primerNombre;
		this.apellidoPaterno = apellidoPaterno;
		this.sexo = sexo;
		this.cedula = cedula;
		this.email = email;
		this.fechaDeNacimiento = fechaDeNacimiento;
		this.nacionalidad = nacionalidad;
		this.idEstadoCivil = idEstadoCivil;
		this.idCiudadResidencia = idCiudadResidencia;
	}

	public ZarDatosPersonales(String foto, String primerNombre,
			String segundoNombre, String apellidoPaterno,
			String apellidoMaterno, boolean sexo, String cedula, String email,
			Date fechaDeNacimiento, String nacionalidad,
			String direccionDomicilio, Boolean discapacidad,
			String telefonoFijo, Boolean movilizacionPropia, Boolean licencia,
			Float salarioActual, Float aspiracionSalarial, int idEstadoCivil,
			int idCiudadResidencia, Integer idTipoDiscapacidad,
			Integer idTipoLicencia) {
		this.foto = foto;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.sexo = sexo;
		this.cedula = cedula;
		this.email = email;
		this.fechaDeNacimiento = fechaDeNacimiento;
		this.nacionalidad = nacionalidad;
		this.direccionDomicilio = direccionDomicilio;
		this.discapacidad = discapacidad;
		this.telefonoFijo = telefonoFijo;
		this.movilizacionPropia = movilizacionPropia;
		this.licencia = licencia;
		this.salarioActual = salarioActual;
		this.aspiracionSalarial = aspiracionSalarial;
		this.idEstadoCivil = idEstadoCivil;
		this.idCiudadResidencia = idCiudadResidencia;
		this.idTipoDiscapacidad = idTipoDiscapacidad;
		this.idTipoLicencia = idTipoLicencia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public boolean isSexo() {
		return this.sexo;
	}

	public void setSexo(boolean sexo) {
		this.sexo = sexo;
	}

	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaDeNacimiento() {
		return this.fechaDeNacimiento;
	}

	public void setFechaDeNacimiento(Date fechaDeNacimiento) {
		this.fechaDeNacimiento = fechaDeNacimiento;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getDireccionDomicilio() {
		return this.direccionDomicilio;
	}

	public void setDireccionDomicilio(String direccionDomicilio) {
		this.direccionDomicilio = direccionDomicilio;
	}

	public Boolean getDiscapacidad() {
		return this.discapacidad;
	}

	public void setDiscapacidad(Boolean discapacidad) {
		this.discapacidad = discapacidad;
	}

	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	public Boolean getMovilizacionPropia() {
		return this.movilizacionPropia;
	}

	public void setMovilizacionPropia(Boolean movilizacionPropia) {
		this.movilizacionPropia = movilizacionPropia;
	}

	public Boolean getLicencia() {
		return this.licencia;
	}

	public void setLicencia(Boolean licencia) {
		this.licencia = licencia;
	}

	public Float getSalarioActual() {
		return this.salarioActual;
	}

	public void setSalarioActual(Float salarioActual) {
		this.salarioActual = salarioActual;
	}

	public Float getAspiracionSalarial() {
		return this.aspiracionSalarial;
	}

	public void setAspiracionSalarial(Float aspiracionSalarial) {
		this.aspiracionSalarial = aspiracionSalarial;
	}

	public int getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(int idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	public int getIdCiudadResidencia() {
		return this.idCiudadResidencia;
	}

	public void setIdCiudadResidencia(int idCiudadResidencia) {
		this.idCiudadResidencia = idCiudadResidencia;
	}

	public Integer getIdTipoDiscapacidad() {
		return this.idTipoDiscapacidad;
	}

	public void setIdTipoDiscapacidad(Integer idTipoDiscapacidad) {
		this.idTipoDiscapacidad = idTipoDiscapacidad;
	}

	public Integer getIdTipoLicencia() {
		return this.idTipoLicencia;
	}

	public void setIdTipoLicencia(Integer idTipoLicencia) {
		this.idTipoLicencia = idTipoLicencia;
	}
	
	public static int obtenerId(String cedula,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarDatosPersonales zdpcr=(ZarDatosPersonales)lista.get(k);
			if(cedula.equals(zdpcr.getCedula()))
				return zdpcr.getId();
        }
		return 0;
	}

}
