package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarDatosPersonalesCiudadResidencia generated by hbm2java
 */
public class ZarDatosPersonalesCiudadResidencia implements java.io.Serializable {

	private Integer id;
	private String nombreCiudad;

	public ZarDatosPersonalesCiudadResidencia() {
	}

	public ZarDatosPersonalesCiudadResidencia(String nombreCiudad) {
		this.nombreCiudad = nombreCiudad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreCiudad() {
		return this.nombreCiudad;
	}

	public void setNombreCiudad(String nombreCiudad) {
		this.nombreCiudad = nombreCiudad;
	}

	public static int obtenerId(String cresidencia,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarDatosPersonalesCiudadResidencia zdpcr=(ZarDatosPersonalesCiudadResidencia)lista.get(k);
			if(cresidencia.equals(zdpcr.getNombreCiudad()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
            ZarDatosPersonalesCiudadResidencia dc=(ZarDatosPersonalesCiudadResidencia)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreCiudad()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}
}
