package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarDatosPersonalesTelefonoCelularOperadora generated by hbm2java
 */
public class ZarDatosPersonalesTelefonoCelularOperadora implements
		java.io.Serializable {

	private Integer id;
	private String nombreOperadora;

	public ZarDatosPersonalesTelefonoCelularOperadora() {
	}

	public ZarDatosPersonalesTelefonoCelularOperadora(String nombreOperadora) {
		this.nombreOperadora = nombreOperadora;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreOperadora() {
		return this.nombreOperadora;
	}

	public void setNombreOperadora(String nombreOperadora) {
		this.nombreOperadora = nombreOperadora;
	}
	
	public static int obtenerId(String operadora,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarDatosPersonalesTelefonoCelularOperadora zdpcr=(ZarDatosPersonalesTelefonoCelularOperadora)lista.get(k);
			if(operadora.equals(zdpcr.getNombreOperadora()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
            ZarDatosPersonalesTelefonoCelularOperadora dc=(ZarDatosPersonalesTelefonoCelularOperadora)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreOperadora()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
