package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarDatosPersonalesTipoLicencia generated by hbm2java
 */
public class ZarDatosPersonalesTipoLicencia implements java.io.Serializable {

	private Integer id;
	private String tipo;

	public ZarDatosPersonalesTipoLicencia() {
	}

	public ZarDatosPersonalesTipoLicencia(String tipo) {
		this.tipo = tipo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	public static int obtenerId(String tlicencia,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarDatosPersonalesTipoLicencia zdpcr=(ZarDatosPersonalesTipoLicencia)lista.get(k);
			if(tlicencia.equals(zdpcr.getTipo()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
            ZarDatosPersonalesTipoLicencia dc=(ZarDatosPersonalesTipoLicencia)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getTipo()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
