package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarDatosPersonalesEstadoCivil generated by hbm2java
 */
public class ZarDatosPersonalesEstadoCivil implements java.io.Serializable {

	private Integer id;
	private String estadoCivil;

	public ZarDatosPersonalesEstadoCivil() {
	}

	public ZarDatosPersonalesEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}
	
	public static int obtenerId(String ecivil,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarDatosPersonalesEstadoCivil zdpec=(ZarDatosPersonalesEstadoCivil)lista.get(k);
			if(ecivil.equals(zdpec.getEstadoCivil()))
				return zdpec.getId();
        }
		return 0;
	}

	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
            ZarDatosPersonalesEstadoCivil dc=(ZarDatosPersonalesEstadoCivil)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getEstadoCivil()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
