package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarExperienciaLaboralSector generated by hbm2java
 */
public class ZarExperienciaLaboralSector implements java.io.Serializable {

	private Integer id;
	private String nombreSector;

	public ZarExperienciaLaboralSector() {
	}

	public ZarExperienciaLaboralSector(String nombreSector) {
		this.nombreSector = nombreSector;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreSector() {
		return this.nombreSector;
	}

	public void setNombreSector(String nombreSector) {
		this.nombreSector = nombreSector;
	}
	
	public static int obtenerId(String sector,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarExperienciaLaboralSector zdpcr=(ZarExperienciaLaboralSector)lista.get(k);
			if(sector.equals(zdpcr.getNombreSector()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarExperienciaLaboralSector zdpcr=(ZarExperienciaLaboralSector)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreSector();
        }
		return " ";
	}

	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarExperienciaLaboralSector dc=(ZarExperienciaLaboralSector)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreSector()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}
}
