package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarExperienciaLaboralArea generated by hbm2java
 */
public class ZarExperienciaLaboralArea implements java.io.Serializable {

	private Integer id;
	private String nombreArea;

	public ZarExperienciaLaboralArea() {
	}

	public ZarExperienciaLaboralArea(String nombreArea) {
		this.nombreArea = nombreArea;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreArea() {
		return this.nombreArea;
	}

	public void setNombreArea(String nombreArea) {
		this.nombreArea = nombreArea;
	}
	
	public static int obtenerId(String area,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarExperienciaLaboralArea zdpcr=(ZarExperienciaLaboralArea)lista.get(k);
			if(area.equals(zdpcr.getNombreArea()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarExperienciaLaboralArea zdpcr=(ZarExperienciaLaboralArea)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreArea();
        }
		return " ";
	}

	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarExperienciaLaboralArea dc=(ZarExperienciaLaboralArea)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreArea()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}
}
