package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarIdiomaNombre generated by hbm2java
 */
public class ZarIdiomaNombre implements java.io.Serializable {

	private Integer id;
	private String nombreIdioma;

	public ZarIdiomaNombre() {
	}

	public ZarIdiomaNombre(String nombreIdioma) {
		this.nombreIdioma = nombreIdioma;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreIdioma() {
		return this.nombreIdioma;
	}

	public void setNombreIdioma(String nombreIdioma) {
		this.nombreIdioma = nombreIdioma;
	}
	
	public static int obtenerId(String idioma,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarIdiomaNombre zdpcr=(ZarIdiomaNombre)lista.get(k);
			if(idioma.equals(zdpcr.getNombreIdioma()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarIdiomaNombre zdpcr=(ZarIdiomaNombre)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreIdioma();
        }
		return " ";
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarIdiomaNombre dc=(ZarIdiomaNombre)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreIdioma()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
