package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarInformaticaConocimiento generated by hbm2java
 */
public class ZarInformaticaConocimiento implements java.io.Serializable {

	private Integer id;
	private String nombreConocimiento;

	public ZarInformaticaConocimiento() {
	}

	public ZarInformaticaConocimiento(String nombreConocimiento) {
		this.nombreConocimiento = nombreConocimiento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreConocimiento() {
		return this.nombreConocimiento;
	}

	public void setNombreConocimiento(String nombreConocimiento) {
		this.nombreConocimiento = nombreConocimiento;
	}
	
	public static int obtenerId(String cono,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarInformaticaConocimiento zdpcr=(ZarInformaticaConocimiento)lista.get(k);
			if(cono.equals(zdpcr.getNombreConocimiento()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	 static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarInformaticaConocimiento zdpcr=(ZarInformaticaConocimiento)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreConocimiento();
        }
		return " ";
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarInformaticaConocimiento dc=(ZarInformaticaConocimiento)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreConocimiento()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
