package com.catani.zar;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarIdioma generated by hbm2java
 */
public class ZarIdioma implements java.io.Serializable {

	private Integer id;
	private String escrito;
	private String oral;
	private String lectura;
	private int idNombre;
	private int idCuenta;

	public ZarIdioma() {
	}

	public ZarIdioma(String escrito, String oral, String lectura, int idNombre,
			int idCuenta) {
		this.escrito = escrito;
		this.oral = oral;
		this.lectura = lectura;
		this.idNombre = idNombre;
		this.idCuenta = idCuenta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEscrito() {
		return this.escrito;
	}

	public void setEscrito(String escrito) {
		this.escrito = escrito;
	}

	public String getOral() {
		return this.oral;
	}

	public void setOral(String oral) {
		this.oral = oral;
	}

	public String getLectura() {
		return this.lectura;
	}

	public void setLectura(String lectura) {
		this.lectura = lectura;
	}

	public int getIdNombre() {
		return this.idNombre;
	}

	public void setIdNombre(int idNombre) {
		this.idNombre = idNombre;
	}

	public int getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(int idCuenta) {
		this.idCuenta = idCuenta;
	}

}
