package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarInformacionAcademicaNivelEstudio generated by hbm2java
 */
public class ZarInformacionAcademicaNivelEstudio implements
		java.io.Serializable {

	private Integer id;
	private String nombreNivel;

	public ZarInformacionAcademicaNivelEstudio() {
	}

	public ZarInformacionAcademicaNivelEstudio(String nombreNivel) {
		this.nombreNivel = nombreNivel;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreNivel() {
		return this.nombreNivel;
	}

	public void setNombreNivel(String nombreNivel) {
		this.nombreNivel = nombreNivel;
	}
	
	public static int obtenerId(String nivel,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarInformacionAcademicaNivelEstudio zdpcr=(ZarInformacionAcademicaNivelEstudio)lista.get(k);
			if(nivel.equals(zdpcr.getNombreNivel()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarInformacionAcademicaNivelEstudio zdpcr=(ZarInformacionAcademicaNivelEstudio)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreNivel();
        }
		return " ";
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarInformacionAcademicaNivelEstudio dc=(ZarInformacionAcademicaNivelEstudio)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreNivel()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
