package com.catani.zar;

import java.util.List;

// Generated 18/08/2012 10:09:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * ZarReferenciaRelacion generated by hbm2java
 */
public class ZarReferenciaRelacion implements java.io.Serializable {

	private Integer id;
	private String nombreRelacion;

	public ZarReferenciaRelacion() {
	}

	public ZarReferenciaRelacion(String nombreRelacion) {
		this.nombreRelacion = nombreRelacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombreRelacion() {
		return this.nombreRelacion;
	}

	public void setNombreRelacion(String nombreRelacion) {
		this.nombreRelacion = nombreRelacion;
	}
	
	public static int obtenerId(String refe,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarReferenciaRelacion zdpcr=(ZarReferenciaRelacion)lista.get(k);
			if(refe.equals(zdpcr.getNombreRelacion()))
				return zdpcr.getId();
        }
		return 0;
	}
	
	public static String obtenerNombre(int id,List lista){
		
		for(int k=0; k<lista.size(); k++)
        {
			ZarReferenciaRelacion zdpcr=(ZarReferenciaRelacion)lista.get(k);
			if(id==zdpcr.getId())
				return zdpcr.getNombreRelacion();
        }
		return " ";
	}
	
	public static String llenarXml(List lista) {
		String xml="";
        xml=xml+"<datos>";
        for(int i=0; i<lista.size(); i++)
        {
        	ZarReferenciaRelacion dc=(ZarReferenciaRelacion)lista.get(i);            
            xml=xml+ "<nombre>"+dc.getNombreRelacion()+"</nombre>";
        }
        xml=xml+"</datos>";
        return xml;
	}

}
